# Required pipeline level variables:
# - `AZ_DEVOPS_DISCORD_WEBHOOK`: For sending out deployment status update in Discord
pool:
  vmImage: windows-latest

trigger: none
pr: none

resources:
  repositories:
    - repository: cms-server
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-cms-server
    - repository: ci
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-ci
  webhooks:
    - webhook: 'Azure CI'
      # Details defined in Azure DevOps service connection
      # > This is the service connection name, not the webhook name.
      connection: 'Pokemon TCGP CI Webhook'
      filters:
        - path: source
          value: pokemon-tcgp-cms-server
        - path: branch
          value: refs/heads/main

variables:
  - template: variables/cache/yarn.yml
  - template: variables/repo/ci.yml
  - template: variables/repo/cms-server.yml

stages:
- stage: Preparation
  jobs:
    - job: Info
      displayName: Trigger Info
      dependsOn: []
      steps:
      - checkout: none

      - powershell: |
          Write-Host '${{ parameters['Azure CI'].commitMessage }}'
          Write-Host '${{ parameters['Azure CI'].link }}'
        displayName: 'Show Trigger Info'

    - job: LintTSC
      displayName: Lint / TSC
      dependsOn: []
      steps:
      - template: templates/checkout/cms-server.yml

      - template: templates/setup/yarn.yml

      - script: yarn run tsc
        displayName: 'Check TypeScript'

      - script: yarn run lint
        displayName: 'Lint Source'

    - job: Test
      displayName: Test
      dependsOn: []
      steps:
        - template: templates/checkout/cms-server.yml

        - template: templates/setup/yarn.yml

        - script: yarn run jest
          displayName: 'Test Source'

- stage: Build
  displayName: Build
  jobs:
    - job: Build
      displayName: Build
      steps:
        - template: templates/checkout/cms-server.yml

        - template: templates/setup/yarn.yml

        - script: yarn run build
          displayName: 'Build App'
          env:
            # Required to make most of the code works properly
            # https://discord.com/channels/1138701819464392744/1201000084276514955/1239977084156383272
            NODE_ENV: production

        - task: ArchiveFiles@2
          displayName: 'Archive Build'
          inputs:
            rootFolderOrFile: .
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'

        - task: PowerShell@2
          displayName: 'Report DevOps Passed'
          inputs:
            filePath: $(CI_DISCORD_WEBHOOK_PATH)
            pwsh: true
          env:
            AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
            AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
            AZ_DEVOPS_STATUS: $(Agent.JobStatus)
            AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
            AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
            AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
            AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
            AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)

- stage: ReportFailure
  displayName: Report Failure
  condition: or(not(succeeded('Preparation')), not(succeeded('Build')))
  jobs:
    - job: ReportFailure
      displayName: Report Failure

      steps:
        - checkout: ci
          path: $(CI_SCRIPTS_REPO_DIR)

        - task: PowerShell@2
          displayName: 'Report Failure'
          inputs:
            filePath: $(CI_DISCORD_WEBHOOK_PATH)
            pwsh: true
          env:
            AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
            AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
            # https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services
            AZ_DEVOPS_STATUS: 'Failed'
            AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
            AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
            AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
            AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
            AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)
