# Required pipeline level variables:
# - `MONGODB_URI`: For storing test data for SSG for next.js
# - `AZ_DEVOPS_DISCORD_WEBHOOK`: For sending out deployment status update in Discord
# - `GITHUB_PAT`: For cloning private submodules in exporter repo
#   - This PAT should have read access to the private submodules to clone.
#   - PAT creation quick URL: https://github.com/settings/personal-access-tokens/new?target_name=RaenonX-PokemonTCGP&expires_in=none&contents=read
pool:
  vmImage: windows-latest

trigger: none
pr: none

resources:
  repositories:
    - repository: exporter
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-exporter
    - repository: ui-core
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-ui-core
      ref: ${{ parameters['Azure CI'].branch }}
    - repository: ci
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-ci
  webhooks:
    - webhook: 'Azure CI'
      # Details defined in Azure DevOps service connection
      # > This is the service connection name, not the webhook name.
      connection: 'Pokemon TCGP CI Webhook'
      filters:
        - path: source
          value: pokemon-tcgp-ui-core
        - path: branch
          value: refs/heads/azure-test-ci

variables:
  - template: /.azure/variables/main.yml
  - template: /.azure/variables/cache/yarn.yml
  - template: /.azure/variables/cache/next.yml
  - template: /.azure/variables/repo/ci.yml
  - template: /.azure/variables/repo/ui-core.yml
  - template: /.azure/variables/repo/exporter.yml

stages:
  - template: /.azure/templates/run/ui-core.yml
    parameters:
      azureWebhookCommitMessage: ${{ parameters['Azure CI'].commitMessage }}
      azureWebhookCommitLink: ${{ parameters['Azure CI'].link }}
